component_depth: 2
languages:
- csharp
- javascript
exclude:
- /CustomerPurchases/wwwroot/.*
- /CustomerPurchases/bin/.*
- /CustomerPurchases/obj/.*
- /CustomerPurchases/Data/Migrations/.*
- /CustomerPurchases/Models/.*
- /CustomerPurchases/Program.cs
- /CustomerPurchases/Startup.cs