// <auto-generated />
using System;
using CustomerPurchases.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CustomerPurchases.Migrations
{
    [DbContext(typeof(PurchaseDbContext))]
    [Migration("20200102153137_TrimmedModels")]
    partial class TrimmedModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CustomerPurchases.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("StockLevel");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hydrogen",
                            StockLevel = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Helium",
                            StockLevel = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lithium",
                            StockLevel = 300
                        });
                });

            modelBuilder.Entity("CustomerPurchases.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<int>("AddressId");

                    b.Property<string>("OrderStatus");

                    b.Property<int>("ProductId");

                    b.Property<int>("Qty");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Purchase");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            AddressId = 1,
                            OrderStatus = "Created",
                            ProductId = 1,
                            Qty = 1,
                            TimeStamp = new DateTime(2020, 1, 2, 15, 31, 36, 413, DateTimeKind.Local).AddTicks(886)
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 1,
                            AddressId = 3,
                            OrderStatus = "Completed",
                            ProductId = 1,
                            Qty = 4,
                            TimeStamp = new DateTime(2020, 1, 2, 15, 31, 36, 415, DateTimeKind.Local).AddTicks(8955)
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 3,
                            AddressId = 2,
                            OrderStatus = "Shipped",
                            ProductId = 3,
                            Qty = 2,
                            TimeStamp = new DateTime(2020, 1, 2, 15, 31, 36, 415, DateTimeKind.Local).AddTicks(8970)
                        });
                });

            modelBuilder.Entity("CustomerPurchases.Models.Purchase", b =>
                {
                    b.HasOne("CustomerPurchases.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
